### ISSUE TITLE
First tab indicator issue

### ISSUE THREAD

**Issue by PavelMartynovN** [Slowyn/react-native-underline-tabbar#13]
First tab indicator is always flickering when I switch between tabs.

**Comment by Slowyn** [comment]
Hm... That's pretty intresting. Can you provide code sample to reproduce this behaviour? Also have you tested it on ios? Does this bug is reproduced there?

**Comment by Slowyn** [comment]
@PavelMartynovN I've fixed possible source of flickering. Please, test it on your case if it's possible for you.

**Comment by PavelMartynovN** [comment]
I tested it. The issue still remains. It can be reproduced on both Android and iOS.
I think that the source of the issue is activeTabTextStyle property. Because it appears only when I use this property.

example
```
renderTabBar={() =>
          <TabBar
            activeTabTextStyle={{ color: "#53ac49", fontSize: 15, fontWeight: 'bold' }}
          />}>
```
